services:
  nats1:
    image: nats:latest
    container_name: nats1
    networks:
      - sandbox
    command: ["-c", "/etc/nats/nats.conf"]
    ports:
      - "4222:4222"   # client
      - "8222:8222"   # monitoring
    volumes:
      - ./nats/nats1.conf:/etc/nats/nats.conf

  nats2:
    image: nats:latest
    container_name: nats2
    networks:
      - sandbox
    command: ["-c", "/etc/nats/nats.conf"]
    ports:
      - "4223:4222"   # client
      - "8223:8222"   # monitoring
    volumes:
      - ./nats/nats2.conf:/etc/nats/nats.conf

networks:
  sandbox:
    name: sandbox
    # driver: bridge
